apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - node-reaper.yaml
configMapGenerator:
  - name: cluster-fleet
    files:
      - agents.json
generatorOptions:
  disableNameSuffixHash: true

