apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
spec:
  interval: 10m
  path: ./deploy/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: raya
