---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: coredns-autoscaler
  namespace: kube-system
spec:
  repo: https://kubernetes-sigs.github.io/cluster-proportional-autoscaler
  chart: cluster-proportional-autoscaler
  version: 1.1.0
  targetNamespace: kube-system
  valuesContent: |
    image:
      tag: v1.10.3
    options:
      target: deployment/coredns
      namespace: kube-system
    config:
      linear:
        nodesPerReplica: 1
        min: 1
    resources:
      requests:
        cpu: 5m
        memory: 10Mi

