# The Hetzner Cloud token the CSI controller authenticates with, in the shape
# the chart expects by default: a Secret named `hcloud` with a `token` key.
# Encrypted with sops; Flux decrypts it at apply time. See deploy/kube-system.yaml.
apiVersion: v1
kind: Secret
metadata:
    name: hcloud
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:wD51bXYQtoa3AyXsc/yl5ojq84c1tksO62qtMiLkbc+HZ11VuGXrtcMtkBUGjtS569DbfFWFi4zbFh2v3XJ1mw==,iv:Cu26/rUxeZLOHximpkzSxeZ96UQ5aXUjzwDWK0HBqxg=,tag:f6lDxqqdseTxIuDdDsfjYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTWwvRVkyNGNHaWVqYUJC
            ZjZMNk9ON3dQTGlBM1Fmd0NYbGl5VWFraVE0CkVDdzl5OUFKNnNzUEM1ZHNzS25k
            NEp1dnJ2UFVvR2J2S3JMcGhUOEFHdjQKLS0tIG9QSlNVdlBlNnlMOTFnWW9zbzZP
            eVp3QU92dUQ3WDQ3TXRtRXZUYlJjSXMKeiTwUi6TWv4xdp1i0DAQ9JshA9eqZwjx
            C7InktETFL2bZia5+0H6daNMv5sV0IVllmhF1Z9ZUQ4n2S0WznNNkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kw23mavskc3ueq62mfstze85aftv5qmmd76x5x4d27tnz9rjlsasxy8fg9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T16:13:20Z"
    mac: ENC[AES256_GCM,data:pgdMa+Q3rHTiTkYDuLnTfHb9ZFaKthtTgwz3fkVs2Hn6qHa1TtrESVjJbkiC52MlQcupUUyAp3B0kdkGikXoFzmOR/qWNcWzk9+jdmSfV0OfvILK4/ikTiTdezUMtL1T2ZYOUPK/jtM1nHbE4nFv+RWunIOegVY7cUwwpgJQUvw=,iv:mjgyYzdFiel4vzuwl1DfRMFjnWZkzbmbm/plOyIcE3c=,tag:r584KejX4DoNK3Sldk0hMg==,type:str]
    version: 3.13.3
