# The Hetzner Cloud token the CSI controller authenticates with, in the shape
# the chart expects by default: a Secret named `hcloud` with a `token` key.
# Encrypted with sops; Flux decrypts it at apply time. See deploy/kube-system.yaml.
apiVersion: v1
kind: Secret
metadata:
    name: hcloud
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:9hFYqPIT/8vN0tvqiRtddsB5SaQPqo0u2lJlLE57wHdq6w==,iv:mN7Kjwr0rrnqdSqnquyaJI3OECNTTy+T3xyft16wOaY=,tag:+YADOfTzbjmqN7rGrZTu1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkR2pENlRTM01KN0NOUm91
            dUxTcHliNHY1eEtJSklaRmxsREZqWTNlbnh3CmZmZDZXZDlKNFFNN1pydG1OeGlJ
            WHR0dGJMNnNrK2duQmpPM0YyY1h6QkUKLS0tIGphQURaZjczNmJ2R0JXY3B6dWZS
            WHc1a095ekFuNS9oT3RTQlg1bEEvRVEKjm4mcTVfOLwIN1eI2eLEupUfAFTNsetW
            wcCyf57z0UGSjH8jjYr955XBdzMa4pWzgxKM2SyqBLy4rTWoGbLYXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kw23mavskc3ueq62mfstze85aftv5qmmd76x5x4d27tnz9rjlsasxy8fg9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T13:53:26Z"
    mac: ENC[AES256_GCM,data:z/7/t9AncFN+elV9QLrN48s/hYGX/FjhRCLgGO2wWS9F6ySxpP/QvHESKK0HIbciT5ykZpIMm0m3BG/XFmuN9pgoBitfjxeaW+ha3tydDpoimeTxFnWVn/3R5mJfIzcg2PnpTGc7eb2DYteA0EsPvQGEES2m+G5pAIX1U7CJvAU=,iv:4FCsoctRi9wYDpKl9svaVAbUiFun8QXgSTVE6mA7u4E=,tag:xKu0kshm2FAjg2H8gx5J1A==,type:str]
    version: 3.13.3
