apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sisu
spec:
  interval: 1h
  url: https://github.com/lthms/sisu
  ref:
    commit: 4697d8d5f91561f3f98fd502256847aa580c9216
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sisu
spec:
  interval: 1h
  chart:
    spec:
      chart: ./charts/sisu
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: sisu
      interval: 1h
  values:
    image:
      repository: ghcr.io/lthms/sisu
      tag: dev-4697d8d5f91561f3f98fd502256847aa580c9216
