apiVersion: v1
kind: Secret
metadata:
    name: r2-backup
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:m9C2BCAixjIWCUOixYaTXmyF7Nz53DlvlDsW1Om+rtI=,iv:Ix8DP8QSQsEs+Z5Jwo3KGdlAfCIK0gaDO8Q0mLC7fcs=,tag:pAcoIwYLQtKGSa4WRb4bsw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:yVnjaoqF/9miMb13IDrTbWJVzZ8INoCpPMfMBsem+NptKUv+E3GK2at2HSWC2CNFUScgJRRnApjfCW7/ISnulw==,iv:PGO70CbCpHDVQJDLNR9PXbOWFbOH0HeTAvoR0gTjO9I=,tag:aRynYAoT+iGIcR4OI1gB3A==,type:str]
    REGION: ENC[AES256_GCM,data:6ErEUg==,iv:3QI3V38jAE5RYg55jBxyKt5sNrffN5U2VgzDlt//j8U=,tag:O3Jcvr/OxpF0gKa56ZhELg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    gcp_kms:
        - created_at: "2026-09-13T15:55:06Z"
          enc: CiQAXZOUpWVU9qavgWf5dOF+990RH8EvxMTAEzlnV4NNb5xooCkSSQCGHyGMYawgKM5R0x9uJimCWBxDFkknZ2qV1Tlx04L8OW5+jI4EQDq0ArzK1P3qOTNbn04bxp9nzN1VS1aoi/cKY1z3jC/XDIg=
          resource_id: projects/raya-dns/locations/europe-west4/keyRings/raya-sops/cryptoKeys/sops
    lastmodified: "2026-09-13T15:55:06Z"
    mac: ENC[AES256_GCM,data:7CMSA43y3Y8qNZFGsV+cMB8P1AUb1YHqkC6hj6BvwHl9O7DuJNhY9iqxewKJ6Mkr7cQppI2E95n0nRC6kuNRxb/ck7YcvG1O+V7hqGlxx3MZIodWnEbXfw3yVxRuZBhfaWZeE4W58a80wiI2FqheXxGwqSQWd/mdHZ1+mOuKVKc=,iv:4tGnxtM437yeQJbBZJUVZ09wkTVFsbNI20OsAG5iaQU=,tag:RtbjRCfBJi818Rup1s6DWw==,type:str]
    version: 3.13.3
