---
apiVersion: v1
kind: Secret
metadata:
    name: r2-backup
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:dCWMrSOk3ITk3p2g93EdvkWXZoAFpLU5gIycMHO8T4E=,iv:Ix8DP8QSQsEs+Z5Jwo3KGdlAfCIK0gaDO8Q0mLC7fcs=,tag:n5XXGtF7Y9/GW4o5sc3QqQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:q6YLHea4bLwcLGYfyLsMB9VE/Idxz60OKNJmAmK9R4m/1sbbXvfXPJGx5hc9OHgzp3wAlqQQpcnbmebRBChiHg==,iv:PGO70CbCpHDVQJDLNR9PXbOWFbOH0HeTAvoR0gTjO9I=,tag:E3gbvE3CdEUq43OrSqLNgw==,type:str]
    REGION: ENC[AES256_GCM,data:N4L+1w==,iv:3QI3V38jAE5RYg55jBxyKt5sNrffN5U2VgzDlt//j8U=,tag:qAc5F4NOquo5aJ+DbLM18A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdHFaQk1BMlVnN0pJREhX
            ckVqc0plWUxPbU5YdnFwNkZsdzFqYm94c2hnCmJUZm5YUTRhNTF4eDVhTFYvenZp
            SFpZUG05SGt4SVBFMEVNNUxkNDZ6dmsKLS0tIDU0WjJzdERpc0ZHQ0R2Y1dmUWpS
            VUVGL3RpZjE3UVZiNjRuKzIzM05UeW8KxAxnLn/p1tYCyxzBK6GmSqWsUFQHIgGA
            SoM2T+3ea+372M69MrFhoebs80u3mbMlyANYOtNeybOjwGId4URxIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kw23mavskc3ueq62mfstze85aftv5qmmd76x5x4d27tnz9rjlsasxy8fg9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T09:45:59Z"
    mac: ENC[AES256_GCM,data:uT0YxxgTQJPBf48K9YhvblWRZpw21OL4c7dk5S2BJHRLzVHnU8aPZP5Z/roAS6Vx4pfS8c1ko/lc5ATxdKxL7Pj25Z++zreAHvWoH5+wz9LmP7uxgC/v2dMNQCIekl0t+R0OY6d0u+e++NpQwJ+ZmgRKQWwMWSHBjJg0cBykGas=,iv:j2UDm++oRT3rgf6b5NAluCbEF1ZO029KlxiYPoayPCk=,tag:kc2w3toEJH7SeC13rN5eOw==,type:str]
    version: 3.13.3
