---
# Connection settings to be handed over to ext-postgres-operator. Defined as a
# Secret because the operator stores its configuration in one.
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
stringData:
  # Fully qualified name to allow cross-namespaces access
  POSTGRES_HOST: postgresql-rw.postgresql.svc.cluster.local:5432
  POSTGRES_URI_ARGS: sslmode=disable
  POSTGRES_DEFAULT_DATABASE: postgres
