name: Provision
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
concurrency: provision
jobs:
  image:
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - uses: hashicorp/setup-packer@v3
        with:
          version: latest
      - run: ./image/build.sh
